services:
  - type: web
    name: sistema-castracao-backend
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: DATABASE_URL
        sync: false
