services:
  - type: web
    name: sistema-castracao-backend
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: cd /opt/render/project && node --max-old-space-size=512 dist/main.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: DATABASE_URL
        sync: false
